# Generated by Django 4.1.5 on 2023-02-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachID', models.BigIntegerField(db_index=True)),
                ('CoachName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryID', models.BigIntegerField(db_index=True)),
                ('CountryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.BigIntegerField(db_index=True)),
                ('GameName', models.CharField(max_length=100)),
                ('GameTime', models.DateField()),
                ('GameTeamType', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeagueID', models.BigIntegerField(db_index=True)),
                ('LeagueName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeagueTypeID', models.BigIntegerField(db_index=True)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.BigIntegerField(db_index=True)),
                ('PlayerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerGameID', models.BigIntegerField(db_index=True)),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.game')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonName', models.CharField(max_length=100)),
                ('SeasonID', models.BigIntegerField(db_index=True)),
                ('SeasonBegin', models.DateField()),
                ('SeasonEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SportID', models.BigIntegerField(db_index=True)),
                ('SportName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueID', models.BigIntegerField(db_index=True)),
                ('VenueName', models.CharField(max_length=100)),
                ('VenueLat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('VenueLon', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamID', models.BigIntegerField(db_index=True)),
                ('TeamName', models.CharField(max_length=100)),
                ('LeagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.league')),
                ('SportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.sport')),
            ],
        ),
        migrations.CreateModel(
            name='StatsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatsTypeID', models.BigIntegerField(db_index=True)),
                ('StatsTypeName', models.CharField(max_length=100)),
                ('SportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SportCountryID', models.BigIntegerField(db_index=True)),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.country')),
                ('SportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.sport')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerTeamID', models.BigIntegerField(db_index=True)),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.player')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerGameStatsID', models.BigIntegerField(db_index=True)),
                ('PlayerGameStatsEvent', models.DateField()),
                ('StatsQuantity', models.DecimalField(decimal_places=8, max_digits=11)),
                ('PlayerGameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.playergame')),
                ('StatsTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.statstype')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='LeagueTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.leaguetype'),
        ),
        migrations.AddField(
            model_name='league',
            name='SportID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.sport'),
        ),
        migrations.AddField(
            model_name='game',
            name='GameTeamID_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamID_1', to='gamechanger.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='GameTeamID_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamID_2', to='gamechanger.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='SeasonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='VenueID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.venue'),
        ),
        migrations.AddField(
            model_name='country',
            name='Sports',
            field=models.ManyToManyField(through='gamechanger.SportCountry', to='gamechanger.sport'),
        ),
        migrations.CreateModel(
            name='CoachTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachTeamID', models.BigIntegerField(db_index=True)),
                ('CoachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.coach')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamechanger.team')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='Teams',
            field=models.ManyToManyField(through='gamechanger.CoachTeam', to='gamechanger.team'),
        ),
    ]
